### ISSUE TITLE
aws_route involving TGW should wait until TGW is attached to VPC

### ISSUE THREAD

**Issue by vivgoyal-aws** [aws-ia/terraform-aws-vpc#101]
I found an issue with terraform-aws-vpc module. 
When using TGW
resource aws_route.public_to_tgw and resource aws_route.private_to_tgw may sometime fail with error that tgw does not exist.

I suspect it happens because
resource aws_ec2_transit_gateway_vpc_attachment.tgw and resource aws_ec2_transit_gateway_route_table_association.tgw are not yet complete.

I think, if aws_routes in question wait for these the TGW VPC attachments and TGW route table association, these errors can be avoided

**Comment by pablo19sc** [comment]
Hi! Yeah I also was experiencing this issue in the last days. Once we merge the current PR to add IPv6, I'll fix this by forcing the depends_on. Thanks for the feedback!

**Comment by pablo19sc** [comment]
Hi! This will be solved once the PR is merged - https://github.com/aws-ia/terraform-aws-vpc/pull/104. Hopefully we will be able to do it latest next week.

**Comment by pablo19sc** [comment]
Already solved in v4.2.0!!
