### ISSUE TITLE
Manage the transit gateway association and propagation using this module?

### ISSUE THREAD

**Issue by joshis2020** [aws-ia/terraform-aws-vpc#103]
Hi,

Going through the transit gateway example [here](https://github.com/aws-ia/terraform-aws-vpc/tree/v4.0.0/examples/transit_gateway) , I saw the way we can add routes pointing to TGW inside the subnet route tables. However, how can we manage the VPC association with the TGW route table and the propogations?

**Comment by pablo19sc** [comment]
Hi!

The propagation and association in the TGW is out of scope of this module. The idea with this one is to simplify all the actions done when configuring a VPC in a specific AWS Account. Later, the management of TGW routing (with all the VPC attachments). The Hub and Spoke module - https://registry.terraform.io/modules/aws-ia/network-hubandspoke/aws/latest - tries to simplify this configuration.
