### ISSUE TITLE
Create subnets dynamically while using IPAM to create the VPC

### ISSUE THREAD

**Issue by DeOriginal** [aws-ia/terraform-aws-vpc#117]
1) I am creating VPCs using IPAM which means that the cidr ranges of the VPC are unknown at runtime. 
2) I am creating multiple private subnets with the option to add or remove more in the future and as stated in ["Updating a VPC with new or removed subnets"](https://github.com/aws-ia/terraform-aws-vpc#updating-a-vpc-with-new-or-removed-subnets), I should set the subnets explicitly.

The question is:
How would I go about setting the subnets explicitly if the cidr of the subnet is unknown?
If it was known I could have used cidrhost, but the ip address is created in the same module.

Thanks in advance

**Comment by drewmullen** [comment]
Hello! Thanks for opening this issue.

If I understand your scenario correctly you are trying to figure out "once a vpc and subnets have been created using a cidr from IPAM, how can I add or remove more subnets?"

Is this accurate?

> How would I go about setting the subnets explicitly if the cidr of the subnet is unknown?

You will have to explicitly set them yourself. Whatever you put in the list the module will attempt to use. The `netmask` is helpful for the initial creation but is limited in what it can do once the network has been created

**Comment by DeOriginal** [comment]
I see,

Thank you for the response!
