### ISSUE TITLE
Allow configure map_public_ip_on_launch

### ISSUE THREAD

**Issue by javier-geko** [aws-ia/terraform-aws-vpc#118]
Hello,

I'm using terraform-aws-vpc module and it's fantastic but for compliance standards I need to set attribute map_public_ip_on_launch to false. I don't need dual-stack, just IPv4.  Is it possible?

Thanks

**Comment by drewmullen** [comment]
Hello , thank you foe opening this issue.

I think atm it is not. @pablo19sc can yall add a option here? 

https://github.com/aws-ia/terraform-aws-vpc/blob/5c6ad426109cac659d1b81d3b59809a8b411b8ca/main.tf#L65

**Comment by pablo19sc** [comment]
Hi @javier-geko working on that! Will send a PR in the following days fixing this.

**Comment by javier-geko** [comment]
thank you!

**Comment by pablo19sc** [comment]
https://github.com/aws-ia/terraform-aws-vpc/pull/121 - this should fix it :) I'll wait to have it merged before closing this issue.

**Comment by pablo19sc** [comment]
Fixed in v4.3.2!
