### ISSUE TITLE
Name tag for Transit Gateway Attachment

### ISSUE THREAD

**Issue by kjenney** [aws-ia/terraform-aws-vpc#120]
I deployed this module today and I noticed that the Transit Gateway attachments aren't tagged. 

The block of code where this is defined is here: https://github.com/aws-ia/terraform-aws-vpc/blob/main/main.tf#L409-L422

Please add the ability to add a Name tag.

**Comment by pablo19sc** [comment]
https://github.com/aws-ia/terraform-aws-vpc/pull/121 - this should fix it :) I'll wait to have it merged before closing this issue. Thanks for the feedback!

**Comment by kjenney** [comment]
Thanks so much 👍

**Comment by pablo19sc** [comment]
Hello everyone! sorry for the delay, I was on PTO... let me work today (and maybe Monday) on this to have it fixed ASAP.

**Comment by kjenney** [comment]
How we doing @pablo19sc? I'm sure this got lost under a pile of other work. Please work on merging this in. Thanks!

**Comment by pablo19sc** [comment]
Fixed in v4.3.2!

**Comment by kjenney** [comment]
Thanks!!
