### ISSUE TITLE
Enhancement - vpc attribute of aws_eip is depreciated

### ISSUE THREAD

**Issue by AdamTylerLynch** [aws-ia/terraform-aws-vpc#125]
│ Warning: Argument is deprecated
│ 
│   with module.vpc.aws_eip.nat,
│   on .terraform/modules/vpc/main.tf line 99, in resource "aws_eip" "nat":
│   99:   vpc      = true
│ 
│ use domain attribute instead

**Comment by shihab-uddin-shakil** [comment]
i got same issue

**Comment by drewmullen** [comment]
Hi thanks for opening this issue. just wanted to clarify - this is only a warning, correct? not an error?

**Comment by da1ight** [comment]
Just change this line to `domain = "vpc"`

**Comment by AdamTylerLynch** [comment]
> 

I have issued a PR to change the declarations.

**Comment by tibistibi** [comment]
it is still on the main documentation site: 

https://registry.terraform.io/modules/terraform-aws-modules/vpc/aws/latest

**Comment by wagnerbianchijr** [comment]
@da1ight removing the `vpc=true` and adding the `domain=vpc` gives me an error when destroying the eip:
```
➜  terraform destroy
╷
│ Error: Value for unconfigurable attribute
│ 
│   with aws_eip.nat_gateway_eip,
│   on main.tf line 92, in resource "aws_eip" "nat_gateway_eip":
│   92:   domain     = "vpc"
│ 
│ Can't configure a value for "domain": its value will be decided automatically based on the result
│ of applying this configuration.
```

**Comment by prakulj12** [comment]
> [@da1ight](https://github.com/da1ight) removing the `vpc=true` and adding the `domain=vpc` gives me an error when destroying the eip:
> 
> ```
> ➜  terraform destroy
> ╷
> │ Error: Value for unconfigurable attribute
> │ 
> │   with aws_eip.nat_gateway_eip,
> │   on main.tf line 92, in resource "aws_eip" "nat_gateway_eip":
> │   92:   domain     = "vpc"
> │ 
> │ Can't configure a value for "domain": its value will be decided automatically based on the result
> │ of applying this configuration.
> ```

+1
