### ISSUE TITLE
Requesting new release to fix deprecated warning

### ISSUE THREAD

**Issue by ablyler** [aws-ia/terraform-aws-vpc#134]
Is it possible to have a new release cut that includes the change that removes the deprecated `vpc = true` line that was fixed in https://github.com/aws-ia/terraform-aws-vpc/commit/df5497ba3c503443571250e7120fb925923e8301? Thanks!

**Comment by pablo19sc** [comment]
Hi! Sorry for that! Done: https://github.com/aws-ia/terraform-aws-vpc/releases/tag/v4.3.1
