### ISSUE TITLE
keys derived from resource attributres that cannot be determined until apply

### ISSUE THREAD

**Issue by ivan-aws** [aws-ia/terraform-aws-vpc#135]
when accessing outputs such as private_subnet_attributes_by_az, terraform throws an error like "...  includes keys derived from resource attributes that cannot be determined until apply". this then requires a targeted apply for the vpc module first before being able to use those outputs. could some of those be exposed with static outputs?

**Comment by drewmullen** [comment]
Hi, thanks for opening this issue.  I dont think this has been a problem for me in the past. Can you share more details and hcl examples around this issue

**Comment by pablo19sc** [comment]
Hi! Closing this Issue as we couldn't replicate the problem and we got no updates since October 2023. Feel free to create a new one if you still are facing this problem. Thanks!
