### ISSUE TITLE
Add option to tag CloudWAN attachments

### ISSUE THREAD

**Issue by nicoaws** [aws-ia/terraform-aws-vpc#145]
It is fairly common for attachment policies to rely on attachment tags to determine which segments to associate an attachment to.

The module should provide a way to indicate the tags to apply to cwan attachments.

**Comment by pablo19sc** [comment]
Hi! Sorry for the delay with this answer. You can tag the Cloud WAN attachments by adding tags to the `core_network` subnet. 

```
core_network = {
    netmask                = 28
    assign_ipv6_cidr       = true
    appliance_mode_support = false
    require_acceptance     = true
    accept_attachment      = true

    tags = {
      env = "prod"
    }
}
```

In this example, the tag `env = prod` will be added to the Core Network subnet, and the Core Network attachment as well.
