### ISSUE TITLE
Possibly a typo, extra closing brace } in public subnet prefix/names

### ISSUE THREAD

**Issue by jslevin4** [aws-ia/terraform-aws-vpc#39]
I notice public subnets have the prefix "public}-" with a brace. I wonder if there is an extra closing brace here:
https://github.com/aws-ia/terraform-aws-vpc/blob/main/main.tf#L58
Thanks!

**Comment by drewmullen** [comment]
Hello :wave: thanks for opening this issue. yes! this is a bug and it is be resolved in #38

**Comment by jslevin4** [comment]
Looks good to me. Thanks!

**Comment by drewmullen** [comment]
resolved in #38 ! thanks for opening this issue
