### ISSUE TITLE
include some examples for data abstraction from outputs

### ISSUE THREAD

**Issue by drewmullen** [aws-ia/terraform-aws-vpc#52]
It's not always immediately obvious how to get specific data out of outputs. for example: how to get a list of subnet_ids

example configuration:
```terraform
module "vpc" {
  source  = "aws-ia/vpc/aws"
  version = ">= 1.0.0"

  name       = "multi-az-vpc"
  cidr_block = "10.0.0.0/20"
  az_count   = 3

  subnets = {
    private = { netmask = 24 }
  }
}
```

list of private subnet_ids
```terraform
> [ for _, value in module.vpc.private_subnet_attributes_by_az: value.id]
[
  "subnet-04a86315c4839b519",
  "subnet-02a7249c8652a7136",
  "subnet-09af79b5329b3681f",
]
```

map of subnet_ids by az
```terraform
> { for key, value in module.vpc.private_subnet_attributes_by_az: key => value.id}
{
  "us-east-1a" = "subnet-04a86315c4839b519"
  "us-east-1b" = "subnet-02a7249c8652a7136"
  "us-east-1c" = "subnet-09af79b5329b3681f"
}
```

**Comment by drewmullen** [comment]
Closed by #53

**Comment by jcvold** [comment]
This example was helpful to get the private and public subnet references, but is there a place/way to see what all of the supported attributes are? What else is available besides `private_subnet_attributes_by_az` and `public_subnet_attributes_by_az`?

**Comment by drewmullen** [comment]
Hi John @jcvold ! Thanks for the Q. So the intent for our outputs is to output the entire resource, including all the attributes. Many modules maintain 100+ outputs for each conceivable value and that is hard to maintain and prone to issues if future upgrades try to change the output names or values.

Example of how this works... 

```
[ for _, value in module.vpc.private_subnet_attributes_by_az: value.id]
[
  "subnet-04a86315c4839b519",
  "subnet-02a7249c8652a7136",
  "subnet-09af79b5329b3681f",
]
```

but where we have `value.id` you can substitute with any attribute that is from `aws_subnet` resource such as [arn](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/subnet#arn) or [availability_zone](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/subnet#availability_zone)

We're open to suggestions on how to document the current behavior more clearly!

Also, is there a specific attribute we're missing or is specifically unclear that i can help clarify? If so, would you mind opening another issue that we can use to track this discussion?
