### ISSUE TITLE
VPC not found when using ipam

### ISSUE THREAD

**Issue by HanwhaARudolph** [aws-ia/terraform-aws-vpc#64]
I am trying to create a VPC with IPAM:
```
module "vpc" {
  source  = "aws-ia/vpc/aws"
  version = ">= 1.0.0"

  name     = var.network_map["example"].suffix
  az_count = 2

  vpc_ipv4_ipam_pool_id   = module.create_ipam.pools_level_2[var.network_map["example"].ipam_region].id
  vpc_ipv4_netmask_length = var.network_map["example"].netmask_length

  subnets = {
    public = {
      netmask                   = 24
      nat_gateway_configuration = "all_azs"
    }
    private = {
      netmask      = 24
      route_to_nat = true
    }
  }
}
```

And the first pass would fail with the following error:
│ Error: AWS SDK Go Service Operation Incomplete
│
│   with module.vpc.awscc_ec2_route_table.public["item"],
│   on .terraform/modules/vpc/main.tf line 47, in resource "awscc_ec2_route_table" "public":
│   47: resource "awscc_ec2_route_table" "public" {
│ Waiting for Cloud Control API service CreateResource operation completion returned: waiter state transitioned to FAILED. StatusMessage: The 
│ 'vpc-XXXXXXXXXXXXXXXXXXX' does not exist (Service: Ec2, Status Code: 400, Request ID: ....

When I tried to rerun it (making no changes) the script would try to destroy the VPC which would fail because of the dependencies. It was trying to destroy the VPC because the first pass already created a VPC which assigned a cidr range and the 2nd pass would have a difference cidr range. I tried to resolve the initial failure by replacing all the vpc_id calls to the following, but it didn't do any good:
 ```
vpc_id             = local.create_vpc ? aws_vpc.main[0].id : local.vpc.id
```
I also tried putting depends-on statements for various resources thinking it might just need time, but that didn't help. It keeps throwing the same error even when its done toward the end of execution. I even put a data command in to check the VPC existed and that works without issue. The VPC does exist when I go look at it in the console so I'm unsure how to resolve this.

**Comment by drewmullen** [comment]
Im guessing you have a hard coded `provider` block for ... setting your destination region, etc... make sure that you also include a provider reference for `awscc` as we use both providers

example if only using for region:
```terraform
provider "aws" {
  region = "us-east-1"
}

provider "awscc" {
  region = "us-east-1"
}
```

**Comment by HanwhaARudolph** [comment]
Yup! That looks like it solved the creation failure, but it did lead me to another issue, but I will open a new issue for that.

**Comment by drewmullen** [comment]
glad that solved it. ill be on the lookout for another issue

thanks for your feedback!
