### ISSUE TITLE
Update to v1.3

### ISSUE THREAD

**Issue by drewmullen** [aws-ia/terraform-aws-vpc#89]
take advantage of new defaults for type `object()`. replace [defaults.tf](https://github.com/aws-ia/terraform-aws-vpc/blob/main/defaults.tf) with new feature

**Comment by pablo19sc** [comment]
Hi! We have this already solved, right? ;)

**Comment by drewmullen** [comment]
Thank you to @pablo19sc for his excellent work on 3.0.1!
