### ISSUE TITLE
AWS provider version constraints require bump to support newer resources

### ISSUE THREAD

**Issue by AdrianBegg** [aws-ia/terraform-aws-vpc#93]
The current version constraint for the AWS provider in the module is set to `>=3.73.0` however the module uses resources that do not exist in this version of the provider specifically `aws_networkmanager_vpc_attachment` and `aws_networkmanager_attachment_accepter`. These resources were added in [`v4.27.0`](https://github.com/hashicorp/terraform-provider-aws/releases/tag/v4.27.0).

If the resolved/matched version of the provider in a child module is below v4.27 the following is thrown:
```
│ Error: Invalid resource type
│
│   on .terraform\modules\vpc\main.tf line 351, in resource "aws_networkmanager_vpc_attachment" "cwan":
│  351: resource "aws_networkmanager_vpc_attachment" "cwan" {
│
│ The provider hashicorp/aws does not support resource type "aws_networkmanager_vpc_attachment".
╵
╷
│ Error: Invalid resource type
│
│   on .terraform\modules\vpc\main.tf line 369, in resource "aws_networkmanager_attachment_accepter" "cwan":
│  369: resource "aws_networkmanager_attachment_accepter" "cwan" {
│
│ The provider hashicorp/aws does not support resource type "aws_networkmanager_attachment_accepter".
```

Further the submodule `modules/flow_logs/modules/s3_log_bucket` uses the `aws_s3_bucket_server_side_encryption_configuration` and `aws_s3_bucket_lifecycle_configuration` resources introduced in [`v4.0.0`](https://github.com/hashicorp/terraform-provider-aws/releases/tag/v4.0.0) however the version constraint is set to `">= 3.72.0"`

```
 Error: Invalid resource type
│
│   on .terraform\modules\vpc\modules\flow_logs\modules\s3_log_bucket\main.tf line 17, in resource "aws_s3_bucket_server_side_encryption_configuration" "flow_logs":
│   17: resource "aws_s3_bucket_server_side_encryption_configuration" "flow_logs" {
│
│ The provider hashicorp/aws does not support resource type "aws_s3_bucket_server_side_encryption_configuration".
╵
╷
│ Error: Invalid resource type
│
│   on .terraform\modules\vpc\modules\flow_logs\modules\s3_log_bucket\main.tf line 27, in resource "aws_s3_bucket_lifecycle_configuration" "flow_logs":
│   27: resource "aws_s3_bucket_lifecycle_configuration" "flow_logs" {
│
│ The provider hashicorp/aws does not support resource type "aws_s3_bucket_lifecycle_configuration".
```

**Comment by drewmullen** [comment]
Thanks for reporting, I'll fix in a bit

There's some misconfiguration with our tfdocs file that keeps knocking down the min version
