### ISSUE TITLE
Replace awscc resources with aws resources

### ISSUE THREAD

**Issue by drewmullen** [aws-ia/terraform-aws-vpc#98]
Replace these resources:
- awscc_ec2_route_table_association
- awscc_ec2_route_table

Make sure tags are still working

Determine if we should remove calls to the label module

**Comment by drewmullen** [comment]
Doc to convert should include instructions for:

- awscc_ec2_route_table_association
- awscc_ec2_route_table
- aws_route

**Comment by drewmullen** [comment]
need to update the cloudwan example, @pablo19sc

**Comment by mbeacom** [comment]
If the intent is to eliminate the `awscc` provider from this module, can we consider archiving this repository all together in favor of existing solutions?
